### ISSUE TITLE
如何找到schoolid

### ISSUE THREAD

**Issue by Lemon-412** [lusao-xg/ChaoXingSign#1]
不同学校的超星平台似乎不太一样
![image](https://user-images.githubusercontent.com/57213526/75742572-fe146780-5d48-11ea-98ad-66b52808e0a3.png)

**Comment by lusao-xg** [comment]
我这个是针对超星平台的，http://i.mooc.chaoxing.com/space/index



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Lemon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月3日(星期二) 中午12:17
收件人:&nbsp;"lusao-xg/ChaoXingSign"<ChaoXingSign@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[lusao-xg/ChaoXingSign] 如何找到schoolid (#1)




不同学校的超星平台似乎不太一样

**Comment by Lemon-412** [comment]
新链接已经检查。我怀疑不同学校登录后超星平台不完全一致，能不能提供一下schoolid和classid等标签的具体位置？

**Comment by lusao-xg** [comment]
上面的链接就是  这两个的位置参考css选择器参考语法body &gt; div &gt; div:nth-child(4) &gt; input&nbsp;

LuSao个人小站：ilusao.cn

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lemon"; 
发送时间: 2020年3月3日(星期二) 中午12:41
收件人: "lusao-xg/ChaoXingSign";
抄送: "LuSao";"Comment";
主题: Re: [lusao-xg/ChaoXingSign] 如何找到schoolid (#1)




新链接已经检查。我怀疑不同学校登录后超星平台不完全一致，能不能提供一下schoolid和classid等标签的具体位置？
 
&mdash;

**Comment by Lemon-412** [comment]
已明确不存在此位置。

**Comment by lusao-xg** [comment]
可以私发账号给我看看吗?邮箱admin@ilusao.cn


&nbsp;

LuSao个人小站：ilusao.cn

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lemon"<notifications@github.com&gt;; 
发送时间: 2020年3月3日(星期二) 中午1:09
收件人: "lusao-xg/ChaoXingSign"<ChaoXingSign@noreply.github.com&gt;; 
抄送: "LuSao"<admin@ilusao.cn&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [lusao-xg/ChaoXingSign] 如何找到schoolid (#1)




已明确不存在此位置。

**Comment by Lemon-412** [comment]
或许是iframe不一样的关系

**Comment by lusao-xg** [comment]
原来是个上海大学的大佬，我没你联系方式  我记错人了 这个不支持手势签到 

发自我的iPhone

**Comment by lusao-xg** [comment]
你的id可以找到，但是是在链接里面 我记得你有我的联系方式，私信我一下
&nbsp;

LuSao个人小站：ilusao.cn

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lemon"<notifications@github.com&gt;; 
发送时间: 2020年3月3日(星期二) 中午1:18
收件人: "lusao-xg/ChaoXingSign"<ChaoXingSign@noreply.github.com&gt;; 
抄送: "LuSao"<admin@ilusao.cn&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [lusao-xg/ChaoXingSign] 如何找到schoolid (#1)




或许是iframe不一样的关系
