### ISSUE TITLE
求教多门科目签到怎么办

### ISSUE THREAD

**Issue by godmei** [lusao-xg/ChaoXingSign#2]
是需要分开成不同的项目还是可以写在config文件里，我试了在后面再添加course id的格式，不过不行，难道是直接用逗号分割就可以吗？

**Comment by lusao-xg** [comment]
每个科目用一个字典保存，存在列表里面  我已经做出了示例，如果无法解决可以添加我微信jkx1577134779

发自我的iPhone

**Comment by godmei** [comment]
谢谢大佬，已经搞明白了
